### ISSUE TITLE
HDR input file + forceTranscode?

### ISSUE THREAD

**Issue by hamzaaftab** [Vanilagy/mediabunny#90]
Thanks for putting together a fantastic library. Running into an issue with a specific file not being able to get converted (suspect it has to do with HDR colormap).

Environment:
- Mac OS
- Chrome Version 139.0.7258.155 (Official Build) (arm64)

Code:
```
const input = new Input({
  source: new BlobSource(file), // (see ffprobe output below for what the file is)
  formats: ALL_FORMATS,
});
const output = new Output({ format: outputFormat, target });
const conversion = await Conversion.init({
  input,
  output,
  video: {
    forceTranscode: true,
  },
});
```

Error:

```
Encoding error.

```

Interestingly when I try to use media sink + media output and iterate over all the samples to convert it that way, I can get the samples from original file, but then writing back still fails with same error.

Crucially: Using Canvas to convert each input sample from HDR to SDR does fix the issue, so perhaps it is related to HDR color profile. Currently trying that approach on top of sink + encode loop, but open to other ideas too.

ffprobe output on input file:
```
ffprobe version 7.1.1 Copyright (c) 2007-2025 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.6)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1.1_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '[REDACTED_PATH]':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : [REDACTED_TIME]
    com.apple.quicktime.location.accuracy.horizontal: [REDACTED]
    com.apple.quicktime.full-frame-rate-playback-intent: 0
    com.apple.quicktime.location.ISO6709: [REDACTED_GPS]
    com.apple.quicktime.make: [REDACTED_DEVICE]
    com.apple.quicktime.model: [REDACTED_DEVICE]
    com.apple.quicktime.software: [REDACTED_DEVICE]
    com.apple.quicktime.creationdate: [REDACTED_TIME]
  Duration: 00:02:01.57, start: 0.000000, bitrate: 13760 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67), 1920x1080, 13413 kb/s, 60 fps, 60 tbr, 600 tbn (default)
      Metadata:
        creation_time   : [REDACTED_TIME]
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : HEVC
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 5, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 4, compression: 0
        displaymatrix: rotation of -90.00 degrees
        Ambient Viewing Environment, ambient_illuminance=314.000000, ambient_light_x=0.312700, ambient_light_y=0.329000
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
      Metadata:
        creation_time   : [REDACTED_TIME]
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D) (default)
      Metadata:
        creation_time   : [REDACTED_TIME]
        handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 23 kb/s (default)
      Metadata:
        creation_time   : [REDACTED_TIME]
        handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 99 kb/s (default)
      Metadata:
        creation_time   : [REDACTED_TIME]
        handler_name    : Core Media Metadata
  Stream #0:5[0x6](und): Data: none (mebx / 0x7862656D), 5 kb/s (default)
      Metadata:
        creation_time   : [REDACTED_TIME]
        handler_name    : Core Media Metadata
  Stream #0:6[0x7](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
      Metadata:
        creation_time   : [REDACTED_TIME]
        handler_name    : Core Media Metadata
```

**Comment by hamzaaftab** [comment]
Some more datapoints:

This does NOT work (encoder error):
```
video: {
  forceTranscode: true,
},
```

This also does NOT work (encoder error):
```
video: {
  forceTranscode: true,
  width: 1080, // original width
},
```

However, this works:
```
video: {
  forceTranscode: true,
  width: 1000, // any value that is different than original
},
```

**Comment by hamzaaftab** [comment]
Actually if we enable forcing shouldRerender to true that also works?

**Comment by Vanilagy** [comment]
Seems to me the encoder doesn't like the HDR frames. When setting the width to something else, it passes through a canvas for the resize step and then the encoder likes it again, because it's being fed the nice SDR canvas frames.

So it could be that this is a bug in Chromium, or that the video encoder just doesn't support encoding HDR frames. Does the encoder error instantly after the first frame?

Would be cool if you could send me the file if possible. Also, is the error truly just "Encoder error"? I've had this before with someone else, and that's way too vague, maybe I messed up the error bubbling logic somewhere.

**Comment by hamzaaftab** [comment]
Sent the file over discord

The encoder seems to error even when i send it one frame

The error is just "Encoder error"

**Comment by Vanilagy** [comment]
So, as I assumed, some encoders don't like the HDR pixel format and error when encoding it. On my Windows machine, it worked perfectly fine by the way, but it did fail on my Mac.

You can see the fix I deployed in the mentioned commit. I now probe the encoder with the first frame to see if it actually supports it. This is much better than doing it with an external flag, since this is not something the user should have to worry about.

Thank you for your input! Will release the fix in a new Mediabunny version, [v1.13.3](https://github.com/Vanilagy/mediabunny/releases/tag/v1.13.3).

**Comment by hamzaaftab** [comment]
Awesome thanks for the quick fix

**Comment by hamzaaftab** [comment]
Hey @Vanilagy.

Just tested and it works overall when not trimming in addition to conversion. However for the same HDR video, if startTimestamp is not exactly 0, then this returns null:
https://github.com/Vanilagy/mediabunny/blob/main/src/conversion.ts#L687

```
const firstSample = await sink.getSample(this._startTimestamp); <<<<<<<<<< null
if (firstSample) {
	try {
		await tempSource.add(firstSample);
		firstSample.close();
		await tempOutput.finalize();
	} catch (error) {
		console.info('Error when probing encoder support. Falling back to rerender path.', error);
		needsRerender = true;
		void tempOutput.cancel();
	}
} else {
	await tempOutput.cancel();
}
```

As a result, it still gets into the "lets not rerender path" and fails. Rerender path still works, even with a startTimestamp != 0 value

**Comment by Vanilagy** [comment]
@hamzaaftab Oh damn good point. I don't really get it though? You saying if _startTimestamp > 0, getSample returns null? That doesn't make any sense to me. If getSample returns something for t1, then it should also returns something for t2 where t2>t1.

Or are you referring to videos where the first sample's timestamp isn't exactly 0, but something slightly above 0 instead? There, I could see the bug happening.

**Comment by hamzaaftab** [comment]
@Vanilagy  For the same video I shared over Discord, this works:

```
const conversion = await Conversion.init({
  input,
  output,
  trim: { start: 0, end: 60 },
  video: {
    forceTranscode: true,
  },
  audio: {
    forceTranscode: true,
  },
});
```

This does not:

```
const conversion = await Conversion.init({
  input,
  output,
  trim: { start: 1, end: 60 },
  video: {
    forceTranscode: true,
  },
  audio: {
    forceTranscode: true,
  },
});
```

Let me trace a bit more and share what I am seeing

in this line:

```
const firstSample = await sink.getSample(this._startTimestamp);
```

when I print it out, this._startTimestamp is 1, firstSample is null, hence it skips the if statement right after it

**Comment by Vanilagy** [comment]
Lowkey seems like a bug with the sample lookup logic. Will look at this later, thank you.

**Comment by hamzaaftab** [comment]
@Vanilagy Did a bit more digging in and think something is up in mediaSamplesAtTimestamps() function, when startTimestamp is 1.0.
- I see that packets are sent to decoder in this timestamp order: 0.9333333333333333 (key, seq 53), 0.9 (delta, seq 54), 0.8833333333333333 (delta, seq 55), 0.9166666666666666 (delta, seq 56), 1 (delta, seq 57)
- The decoder flush() is called
- It only outputs decoded samples for 0.8833333333333333, then 0.9
- None of these match timestampsOfInterest = 1 +/- epsilion

If I force feed slightly more packets than we do with the current code, I end up receiving the packet at timestamp=1. The packets in decode order ahead of packet with PTS=1 actually have PTS less than 1. The next packets in the sequence after 57 are 0.9666666666666667 (delta, seq 58), .....

Based on my experience, the decoder will not output decoded sample for PTS=1 until we have sent it all packets ahead with PTS <1 (which can be the case when PTS and DTS are written out of order). Think decoder only likes to output in PTS order (so its waiting to output seq 58 before outputting seq 57 but we never sent it seq 58). 

I think if we send also the few frames ahead of the packet we want that have PTS < the packet we want, it may fix it?

**Comment by Vanilagy** [comment]
Hey, thanks for diging! There might be some out-of-order stuff going on here. I'll look into tomorrow, thanks!

**Comment by Vanilagy** [comment]
Fixed in v1.14.1. The Conversion API bug is fixed, it now simply uses the first sample to check encoder support rather than the one at the provided timestamp, which honestly is better anyway, since it's guaranteed to be a key frame which makes the check way faster.

I was able to reproduce the issue in `mediaSamplesAtTimestamps`, it does seem like the decoder is refusing to emit the packets as samples even when flushed, and it might need some additional "force-feeding". The fix is probably going to be non-trivial. I added to my list. I am planning a complete refactor (including new API) of this feature anyway, and I think I'll just do the fix when I get to that.

**Comment by Vanilagy** [comment]
Alright, the `mediaSamplesAtTimestamps` is now also fixed.

**Comment by hamzaaftab** [comment]
Thank you for fixing!
